// data.js — bilingual UI strings + mock dataset for the Gaokao voice refactor.
// Loaded as a global so the DC logic + template can read it. window.GK = { STR, ... }.
(function () {
  // ---- UI chrome strings (cn / en) ----
  const STR = {
    cn: {
      brand: '反思志愿',
      tagline: '不替你做决定,帮你想清楚自己到底想要什么',
      demoBadge: '演示模式',
      liveBadge: '已连接',
      langBtn: 'EN',
      // launch
      launchKicker: '高考志愿 · 反思均衡',
      launchTitle: '走一趟,照见你自己',
      expectTitle: '接下来会发生什么',
      expect: [
        '从头到尾都靠说,你开口就行,上一个问题答完会自动退场',
        '先说说你在纠结哪几个「专业@学校」,以及你对每个已经知道些什么',
        '每一站,两个「平行宇宙里的你」会各自抛来一个尖锐的问题。它把每个选择往「模拟人生」里走几步,把你没掂量过的取舍摆在你面前。',
        '想重新排选择的顺序,随时都行,改主意很正常',
        '走到你觉得够了就停。最后给你的是一面照你自己的镜子,它不会告诉你答案。',
      ],
      voiceNote: '要用到麦克风。不方便出声,也可以每一步都打字。',
      startBtn: '开始这趟旅程',
      // mic
      micIdle: '点一下麦克风,开口说',
      micListening: '正在听……(再点一下结束)',
      micThinking: '正在听懂你……',
      micKeyboard: '改用键盘',
      micRetry: '重说一次',
      nextBtn: '下一步',
      addMore: '我想补充',
      youSaid: '我听到的是',
      typePlaceholder: '在这里打字……',
      submitBtn: '好了',
      // rerank
      rerankTitle: '把它们排个序',
      rerankLead: '凭现在的感觉,把你最想去的放在最上面。点箭头调整。',
      rerankContinue: '就这样,继续',
      rerankAgain: '重新排一下',
      // stop
      stopKicker: '第 {n} 站',
      stopThisStop: '这一站想帮你想清楚',
      stopFutureA: '选了这条路的你',
      stopFutureB: '选了另一条路的你',
      stopMicLead: '你怎么看?改主意了吗?',
      // end choice
      endChoiceKicker: '要继续吗?',
      endChoiceTitle: '你已经走过了最该想清楚的几站',
      endChoiceLead: '剩下的站会越来越细。你可以就此收尾,看看这一路照见的你,也可以再往下走几站。',
      endFinish: '完成旅途',
      endNext: '再走一站',
      cornerEnd: '完成旅途',
      // ending
      endingKicker: '这趟走完了',
      endingTitle: '这是你照出来的自己',
      endingPortrait: '价值画像',
      endingShift: '排序怎么变的',
      endingStart: '开始',
      endingFinal: '最后',
      endingConf: '走完之后,你对第 1 名有多确定?',
      endingConfWas: '开始时',
      endingReportTitle: '你的反思小结',
      endingReplay: '再走一趟',
      // report sections
      reKicker: '一点说明',
      reTitle: '关于「不后悔的选择」',
      reBody: ['反思均衡说的是,你的具体排序和你心里真正看重的东西能互相对上,不打架。', '一个让你不后悔的选择,往往是你已经看清它的代价,还愿意为它买单。这趟走下来,你大概更清楚自己愿意为什么买单了。'],
      statScenesLabel: '走过的站',
      statScenesUnit: '站',
      statLingerLabel: '感触最多的一站',
      statDwellLabel: '用时最久的一站',
      statSwitchLabel: '调整排序',
      statSwitchUnit: '次',
      bumpTitle: '你的排序是怎么走的',
      bumpEmpty: '这一趟你没怎么动排序。',
      bumpStart: '开始',
      changesTitle: '每次改动,和你当时的理由',
      changesEmpty: '你一路保持着同一个排序。',
      changeReasonSaid: '你当时说',
      changeTopTo: '把「{x}」排到了第一',
      changeReorder: '动了动顺序',
      changeMindTitle: '会让你改变主意的事',
      changeMindLead: '这些是你在每一站后,说出来的「本可以」。',
      changeMindEmpty: '这一趟你没怎么留下「本可以」。',
      shiftsTitle: '一开始的你',
      shiftsLead: '下面是你最开始说的话,挑出来给你自己对照。哪些后来松动了?',
      shiftsNote: '自动判断「哪些高层想法变了」需要更深的语言分析,这里先把你最初的原话放出来,供你自己回看。',
      // post-stop rerank voice capture
      rerankWhatChanged: '你刚调整了顺序。假想一下，什么样的信息或情况,才可能让你坚持原来的排法?',
      rerankWhatSame: '你没有改顺序。假想一下，什么样的信息或情况,才可能让你改变排法?',
      rerankSkip: '跳过,直接继续',
      loading: '正在展开下一站……',
    },
    en: {
      brand: 'Reflect',
      tagline: "It won't decide for you. It helps you figure out what you actually want.",
      demoBadge: 'DEMO',
      liveBadge: 'LIVE',
      langBtn: '中文',
      launchKicker: 'College choice · Reflective equilibrium',
      launchTitle: 'Walk it through. See yourself.',
      expectTitle: "Here's what happens",
      expect: [
        'You do it all by talking. Just speak, and once you answer a question it steps aside for the next.',
        "First, say which major@university pairs you're torn between, and what you already know about each.",
        'At every stop, two "yous from parallel universes" each throw you one sharp question. It walks each choice a few steps into a simulated life and puts the trade-offs you had not weighed in front of you.',
        'Reorder your choices whenever you like. Changing your mind is completely normal.',
        "Stop once you've had enough. What you walk away with is a mirror that shows you yourself, and it does not hand you an answer.",
      ],
      voiceNote: "It uses your microphone. If you can't speak right now, you can type at every step too.",
      startBtn: 'Begin the journey',
      micIdle: 'Tap the mic and start talking',
      micListening: 'Listening… (tap again to stop)',
      micThinking: 'Making sense of it…',
      micKeyboard: 'Use keyboard',
      micRetry: 'Say it again',
      nextBtn: 'Next',
      addMore: 'Add more',
      youSaid: 'What I heard',
      typePlaceholder: 'Type here…',
      submitBtn: 'Done',
      rerankTitle: 'Put them in order',
      rerankLead: 'Going on how you feel right now, put the one you most want at the top. Tap the arrows.',
      rerankContinue: 'Looks right, continue',
      rerankAgain: 'Re-order',
      stopKicker: 'Stop {n}',
      stopThisStop: 'This stop wants to help you settle',
      stopFutureA: 'The you who took this road',
      stopFutureB: 'The you who took the other road',
      stopMicLead: 'What do you think? Changed your mind?',
      endChoiceKicker: 'Keep going?',
      endChoiceTitle: "You've walked through the stops that matter most",
      endChoiceLead: 'The remaining stops get finer-grained. You can wrap up now and see the you this walk has surfaced, or take a few more.',
      endFinish: 'Finish the journey',
      endNext: 'One more stop',
      cornerEnd: 'Finish',
      endingKicker: 'The walk is done',
      endingTitle: 'This is the you it surfaced',
      endingPortrait: 'Value portrait',
      endingShift: 'How the order moved',
      endingStart: 'Start',
      endingFinal: 'End',
      endingConf: 'After all that, how sure are you about #1?',
      endingConfWas: 'At the start',
      endingReportTitle: 'Your reflection',
      endingReplay: 'Walk it again',
      // report sections
      reKicker: 'A note',
      reTitle: 'On choices you can live with',
      reBody: ['Reflective equilibrium means your actual ranking and the things you really care about line up, instead of fighting each other.', "A choice you can live with is usually one whose cost you've seen clearly and still want to pay. After this walk, you probably know a little better what you're willing to pay for."],
      statScenesLabel: 'Stops walked',
      statScenesUnit: '',
      statLingerLabel: 'The stop that hit hardest',
      statDwellLabel: 'The stop you lingered on longest',
      statSwitchLabel: 'Order changes',
      statSwitchUnit: '',
      bumpTitle: 'How your ranking moved',
      bumpEmpty: "You barely touched the order this time.",
      bumpStart: 'Start',
      changesTitle: 'Each change, and your reason at the time',
      changesEmpty: 'You kept the same order all the way through.',
      changeReasonSaid: 'You said',
      changeTopTo: 'moved "{x}" to first',
      changeReorder: 'shuffled the order',
      changeMindTitle: 'Things that would change your mind',
      changeMindLead: 'These are the "what ifs" you said out loud after each stop.',
      changeMindEmpty: "You didn't leave many 'what ifs' this time.",
      shiftsTitle: 'The you from the start',
      shiftsLead: 'Here is what you said at the very beginning, pulled out for you to check against. What has loosened since?',
      shiftsNote: 'Telling automatically which high-level ideas shifted needs deeper language analysis. For now this shows your original words so you can look back yourself.',
      rerankWhatChanged: 'You just changed the order. What would have made you keep your earlier ranking?',
      rerankWhatSame: 'You kept the same order. What would have made you change your ranking?',
      rerankSkip: 'Skip and continue',
      loading: 'Opening the next stop…',
    },
  };

  const pair = (cn, en) => ({ cn, en });

  // ---- mock pairs (major @ university) ----
  const PAIRS = [
    { id: 'p1', label: pair('临床医学 @ 中山大学', 'Clinical Medicine @ Sun Yat-sen U.'), color: '#BC6242',
      know: pair('听说很苦,要读很多年,但工作稳定,家里也希望我学医。',
                 "I hear it's brutal and takes many years, but it's stable, and my family wants me in medicine.") },
    { id: 'p2', label: pair('计算机科学与技术 @ 华南理工大学', 'Computer Science @ SCUT'), color: '#3873A8',
      know: pair('工资高,机会多,但好像很卷,也怕被 AI 取代。',
                 'Pays well and has lots of openings, but it looks cut-throat, and I worry about being replaced by AI.') },
    { id: 'p3', label: pair('金融学 @ 上海财经大学', 'Finance @ SUFE'), color: '#53984F',
      know: pair('在上海,听起来很体面,但不确定自己是不是真的喜欢。',
                 "It's in Shanghai and sounds prestigious, but I'm not sure I actually like it.") },
    { id: 'p4', label: pair('法学 @ 中国政法大学', 'Law @ CUPL'), color: '#7E55A4',
      know: pair('想做点和公平有关的事,但听说法考很难,前几年很熬。',
                 'I want to do something about fairness, but I hear the bar exam is hard and the first years are rough.') },
  ];

  // ---- intake voice questions (besides the per-pair "what do you know" ones) ----
  const INTAKE = {
    pairs: { id: 'pairs',
      prompt: pair('先说说,你在纠结哪几个「专业@学校」?', 'First, which major@university pairs are you torn between?'),
      hint: pair('说 2 到 6 个就好,不用想得太全。', 'Two to six of them is plenty. No need to be exhaustive.'),
      mock: pair('我在临床医学中山大学、计算机华南理工、金融上海财经,还有法学中国政法之间纠结。',
                 "I'm torn between clinical medicine at Sun Yat-sen, CS at SCUT, finance at SUFE, and law at CUPL.") },
    perPair: {
      promptCn: (l) => `关于「${l}」,你已经知道些什么?`,
      promptEn: (l) => `What do you already know about "${l}"?`,
      hint: pair('随便聊聊你的印象、担心,或者听来的说法。', "Just share your impressions, your worries, or anything you've heard.") },
    tail: [
      { id: 'struggle',
        prompt: pair('你最纠结的,到底是什么?', 'What are you most torn about?'),
        hint: pair('', ''),
        mock: pair('家里特别希望我学医,觉得稳定。可我心里更想做点自由、有创造的事。',
                   "My family really wants me in medicine because it's stable. But honestly I'd rather do something freer and more creative.") },
      { id: 'macro',
        prompt: pair('对以后的人生,你有什么大方向上的想法?', 'For your life ahead, what do you want in the big picture?'),
        hint: pair('不用具体,说说你想要怎样的生活。', "It doesn't have to be concrete. Just the kind of life you want."),
        mock: pair('我想要生活能稳一点,但又不想一眼望到头,最好还能做点自己觉得有意义的事。',
                   'I want some stability, though I would hate a life I can already see to the end of. Ideally something that feels meaningful too.') },
      { id: 'values',
        prompt: pair('钱、兴趣、影响力,你最看重哪个?', 'Money, interest, impact. Which matters most to you?'),
        hint: pair('排个序,或者说说它们之间怎么权衡。', 'Rank them, or talk through how you weigh them.'),
        mock: pair('兴趣最重要,其次是影响力,钱够用就行,但也不能太少。',
                   'Interest matters most, then impact. Money just needs to be enough, though not too little.') },
      { id: 'dest',
        prompt: pair('毕业以后,你更想走哪条路?国内升学、出国留学、私企就业、国企就业、考公考编、创业,还是其他?', 'After graduating, which way do you lean? Grad school in China, study abroad, a private-sector job, a state-owned job, civil service exams, starting something, or other?'),
        hint: pair('还没想好也没关系,说说倾向就行。', "It's fine to be unsure. Just your leaning."),
        mock: pair('大概率会想读研,先把专业学扎实,出国也不排斥。',
                   "Probably grad school, to get a solid footing first. I'm open to going abroad too.") },
      { id: 'conf',
        prompt: pair('现在,你对排在第一的那个有多确定?', 'Right now, how sure are you about your number one?'),
        hint: pair('用「不太确定」到「非常确定」之间的话说说。', 'Anywhere from "not really" to "very sure".'),
        mock: pair('说实话不太确定,大概一半一半吧,所以才来走这一趟。',
                   "Honestly not very. Maybe fifty-fifty. That's why I'm here.") },
    ],
  };

  // ---- mock rethink stops ----
  const STOPS = [
    { factorKey: 'course_and_academic', factor: pair('课程与学业', 'Coursework & study'),
      high: pair('你选的专业,大一大二真正要学的课、强度和方向,你扛得住、也喜欢吗?',
                 'The courses you will actually take in years one and two, the workload, the direction. Can you carry it, and do you like it?'),
      futureA: { color: '#BC6242', pose: 'think', mood: 'sad',
        q: pair('如果有一天,你连着五年泡在解剖楼和病理切片里,同龄人早已上班,你还在背不完的考点里熬夜,你受得了吗?',
                "What if one day you spend five straight years among cadaver labs and pathology slides, your peers already working while you're still up at night on endless exam points. Could you bear that?") },
      futureB: { color: '#3873A8', pose: 'shrug', mood: 'confused',
        q: pair('如果有一天,你刚啃完的技术框架半年就过时,得不停自学才追得上,没人给你标准答案,你受得了吗?',
                'What if one day the stack you just mastered goes obsolete in half a year, you have to keep teaching yourself to stay current, and no one hands you the answer. Could you bear that?') },
      mic: pair('哪一种更让你怕?说说看,也可以改主意。', 'Which one scares you more? Talk it through, and feel free to change your mind.') },

    { factorKey: 'economic_and_return', factor: pair('经济与回报', 'Money & return'),
      high: pair('这条路的经济回报,和你、和家里需要的,对得上吗?',
                 'Does the money this road pays line up with what you and your family need?'),
      futureA: { color: '#BC6242', pose: 'think', mood: 'sad',
        q: pair('如果有一天,你规培几年只拿微薄补贴,同学早就年薪可观,你三十岁才算真正开始挣钱,你受得了吗?',
                'What if one day you spend years in residency on a tiny stipend while classmates already earn real money, and you only start truly earning at thirty. Could you bear that?') },
      futureB: { color: '#53984F', pose: 'shrug', mood: 'confused',
        q: pair('如果有一天,你拿着漂亮的起薪,却被业绩和行情拴着,行业一冷大家都人人自危,你受得了吗?',
                'What if one day you draw a great starting salary but stay chained to targets and the market, and one downturn has everyone fearing for their job. Could you bear that?') },
      mic: pair('钱对你到底有多重要?诚实一点。', 'How much does money really matter to you? Be honest.') },

    { factorKey: 'career_prospect', factor: pair('职业前景', 'Career prospects'),
      high: pair('把时间拉长到十年,这条路通向的地方,是你想去的吗?',
                 'Stretch it out ten years. Is where this road leads somewhere you want to be?'),
      futureA: { color: '#BC6242', pose: 'think', mood: 'neutral',
        q: pair('如果有一天,你终于熬成主治,日子被夜班和医患关系填满,想抽身去过别的人生却很难,你受得了吗?',
                'What if one day you finally make attending physician, but your days fill with night shifts and patient tensions, and stepping away for another kind of life gets very hard. Could you bear that?') },
      futureB: { color: '#7E55A4', pose: 'point', mood: 'neutral',
        q: pair('如果有一天,你考过了最难的法考,头几年却薪水微薄、案子琐碎,熬出头遥遥无期,你受得了吗?',
                'What if one day you pass the hardest bar exam, but the first years pay little on small cases, and breaking through still feels far off. Could you bear that?') },
      mic: pair('十年后的你,会感谢现在的选择吗?', 'Would the you of ten years from now thank you for this choice?') },

    { factorKey: 'city_and_opportunity', factor: pair('城市与机会', 'City & opportunity'),
      high: pair('你要待的城市,给得了你想要的机会和生活吗?',
                 'Can the city you will live in give you the opportunities and the life you want?'),
      futureA: { color: '#BC6242', pose: 'think', mood: 'sad',
        q: pair('如果有一天,你被分到一座小城的医院,稳定却安静,大城市的热闹和机会都跟你没关系,你受得了吗?',
                'What if one day you are posted to a hospital in a small city, stable but quiet, and the buzz and opportunity of big cities have nothing to do with you. Could you bear that?') },
      futureB: { color: '#3873A8', pose: 'shrug', mood: 'confused',
        q: pair('如果有一天,你挤在一线城市的格子间,机会很多,房租和通勤也很多,想落脚都难,你受得了吗?',
                'What if one day you are squeezed into a cubicle in a first-tier city, with plenty of opportunity but plenty of rent and commute too, and even getting a foothold is hard. Could you bear that?') },
      mic: pair('你想要的,是稳,还是闯?', 'What do you want more, to settle or to strive?') },

    { factorKey: 'cost_and_sacrifice', factor: pair('代价与放弃', 'Cost & sacrifice'),
      high: pair('选了这条路,你其实放弃了什么?那个代价,你认吗?',
                 'Take this road and what are you really giving up? That cost, do you own it?'),
      futureA: { color: '#BC6242', pose: 'think', mood: 'neutral',
        q: pair('如果有一天,你成了别人眼里的好医生,却很少有时间画画、旅行、陪想陪的人,你受得了吗?',
                "What if one day you become everyone's idea of a good doctor, but rarely have time to paint, to travel, or to be with the people you want. Could you bear that?") },
      futureB: { color: '#53984F', pose: 'shrug', mood: 'confused',
        q: pair('如果有一天,你做着自由又喜欢的事,却得一个人扛起所有不确定,没人替你兜底,你受得了吗?',
                'What if one day you do the free thing you love, but carry all the uncertainty alone, with no one to catch you. Could you bear that?') },
      mic: pair('为了想要的,你愿意放下什么?', 'For what you want, what are you willing to put down?') },
  ];

  // ---- mock ending ----
  const ENDING = {
    portrait: pair(
      '你嘴上说想稳,但每一站真正让你停下来的,都是「会不会被框住」「还做不做得了自己喜欢的事」。辛苦你扛得住,你更在意的是别把选择的余地弄丢。你想走的,是一条以后还能改写的路。',
      "You say you want stability, but at every stop the thing that actually stopped you was whether you'd be boxed in, and whether you'd still get to do what you love. You can handle hard work. What you really mind is losing room to choose. The road you want is one you can still rewrite later."),
    report: pair(
      ['你这一路一直绕回同一个张力,稳定和自由。你想要稳定带来的安全感,又舍不得自由留下的余地。',
       '它们未必只能二选一。接下来值得你去查证的是,每条路能不能各占一点。医学里有没有相对自由的方向?走自由那条路,能不能给自己搭一张安全网?',
       '这份小结不会替你下结论。它只是把你这一路已经露出来的倾向说给你听,你可以拿去和家人、朋友再聊聊。'],
      ['You kept circling back to one tension, stability and freedom. You want the security stability brings, and you cannot quite give up the room freedom leaves you.',
       'They may not have to be a choice between two. Worth checking next is whether each road can hold a little of both. Is there a freer direction inside medicine? On the freer road, can you build yourself a safety net?',
       "This summary won't conclude anything for you. It just says back to you the leanings you've already shown, so you can take them to family and friends."]),
  };

  window.GK = { STR, PAIRS, INTAKE, STOPS, ENDING };
})();
