// data.js — bilingual UI strings + intake question structure for the Gaokao voice refactor.
// Loaded as a global so the DC logic + template can read it. window.GK = { STR, INTAKE }.
(function () {
  // ---- UI chrome strings (cn / en) ----
  const STR = {
    cn: {
      brand: '反思志愿',
      tagline: '不替你做决定,帮你想清楚自己到底想要什么',
      demoBadge: '演示模式',
      liveBadge: '已连接',
      langBtn: 'EN',
      // launch
      launchKicker: '高考志愿 · 反思均衡',
      launchTitle: '走一趟,照见你自己',
      expectTitle: '接下来会发生什么',
      expect: [
        '从头到尾都靠说,你开口就行,上一个问题答完会自动退场',
        '先说说你在纠结哪几个「专业@学校」,以及你对每个已经知道些什么',
        '每一站,两个「平行宇宙里的你」会各自抛来一个尖锐的问题。它把每个选择往「模拟人生」里走几步,把你没掂量过的取舍摆在你面前。',
        '想重新排选择的顺序,随时都行,改主意很正常',
        '走到你觉得够了就停。最后给你的是一面照你自己的镜子,它不会告诉你答案。',
      ],
      voiceNote: '要用到麦克风。不方便出声,也可以每一步都打字。',
      startBtn: '开始这趟旅程',
      // mic
      micIdle: '点一下麦克风,开口说',
      micListening: '正在听……(再点一下结束)',
      micThinking: '正在听懂你……',
      micKeyboard: '改用键盘',
      micRetry: '重说一次',
      nextBtn: '下一步',
      addMore: '我想补充',
      youSaid: '我听到的是',
      typePlaceholder: '在这里打字……',
      submitBtn: '好了',
      // rerank
      rerankTitle: '把它们排个序',
      rerankLead: '凭现在的感觉,把你最想去的放在最上面。点箭头调整。',
      rerankContinue: '就这样,继续',
      rerankAgain: '重新排一下',
      // stop
      stopKicker: '第 {n} 站',
      stopThisStop: '这一站想帮你想清楚',
      stopFutureA: '选了这条路的你',
      stopFutureB: '选了另一条路的你',
      stopMicLead: '你怎么看?改主意了吗?',
      investigatorTitle: '调查者视角',
      // end choice
      endChoiceKicker: '要继续吗?',
      endChoiceTitle: '你已经走过了最该想清楚的几站',
      endChoiceLead: '剩下的站会越来越细。你可以就此收尾,看看这一路照见的你,也可以再往下走几站。',
      endFinish: '完成旅途',
      endNext: '再走一站',
      cornerEnd: '完成旅途',
      // ending
      endingKicker: '这趟走完了',
      endingTitle: '这是你照出来的自己',
      endingPortrait: '价值画像',
      endingShift: '排序怎么变的',
      endingStart: '开始',
      endingFinal: '最后',
      endingConf: '走完之后,你对第 1 名有多确定?',
      endingConfWas: '开始时',
      endingReportTitle: '你的反思小结',
      endingReplay: '再走一趟',
      // report sections
      reKicker: '一点说明',
      reTitle: '关于「不后悔的选择」',
      reBody: ['反思均衡说的是,你的具体排序和你心里真正看重的东西能互相对上,不打架。', '一个让你不后悔的选择,往往是你已经看清它的代价,还愿意为它买单。这趟走下来,你大概更清楚自己愿意为什么买单了。'],
      statScenesLabel: '走过的站',
      statScenesUnit: '站',
      statLingerLabel: '感触最多的一站',
      statDwellLabel: '用时最久的一站',
      statSwitchLabel: '调整排序',
      statSwitchUnit: '次',
      bumpTitle: '你的排序是怎么走的',
      bumpEmpty: '这一趟你没怎么动排序。',
      bumpStart: '开始',
      changesTitle: '每次改动,和你当时的理由',
      changesEmpty: '你一路保持着同一个排序。',
      changeReasonSaid: '你当时说',
      changeTopTo: '把「{x}」排到了第一',
      changeReorder: '动了动顺序',
      changeMindTitle: '会让你改变主意的事',
      changeMindLead: '这些是你在每一站后,说出来的「本可以」。',
      changeMindEmpty: '这一趟你没怎么留下「本可以」。',
      shiftsTitle: '一开始的你',
      shiftsLead: '下面是你最开始说的话,挑出来给你自己对照。哪些后来松动了?',
      shiftsNote: '自动判断「哪些高层想法变了」需要更深的语言分析,这里先把你最初的原话放出来,供你自己回看。',
      // post-stop rerank voice capture
      rerankWhatChanged: '你刚调整了顺序。假想一下，什么样的信息或情况,才可能让你坚持原来的排法?',
      rerankWhatSame: '你没有改顺序。假想一下，什么样的信息或情况,才可能让你改变排法?',
      rerankSkip: '跳过,直接继续',
      loading: '正在展开下一站……',
      backendUnavailable: '后端暂时连不上,请稍后再试。',
    },
    en: {
      brand: 'Reflect',
      tagline: "It won't decide for you. It helps you figure out what you actually want.",
      demoBadge: 'DEMO',
      liveBadge: 'LIVE',
      langBtn: '中文',
      launchKicker: 'College choice · Reflective equilibrium',
      launchTitle: 'Walk it through. See yourself.',
      expectTitle: "Here's what happens",
      expect: [
        'You do it all by talking. Just speak, and once you answer a question it steps aside for the next.',
        "First, say which major@university pairs you're torn between, and what you already know about each.",
        'At every stop, two "yous from parallel universes" each throw you one sharp question. It walks each choice a few steps into a simulated life and puts the trade-offs you had not weighed in front of you.',
        'Reorder your choices whenever you like. Changing your mind is completely normal.',
        "Stop once you've had enough. What you walk away with is a mirror that shows you yourself, and it does not hand you an answer.",
      ],
      voiceNote: "It uses your microphone. If you can't speak right now, you can type at every step too.",
      startBtn: 'Begin the journey',
      micIdle: 'Tap the mic and start talking',
      micListening: 'Listening… (tap again to stop)',
      micThinking: 'Making sense of it…',
      micKeyboard: 'Use keyboard',
      micRetry: 'Say it again',
      nextBtn: 'Next',
      addMore: 'Add more',
      youSaid: 'What I heard',
      typePlaceholder: 'Type here…',
      submitBtn: 'Done',
      rerankTitle: 'Put them in order',
      rerankLead: 'Going on how you feel right now, put the one you most want at the top. Tap the arrows.',
      rerankContinue: 'Looks right, continue',
      rerankAgain: 'Re-order',
      stopKicker: 'Stop {n}',
      stopThisStop: 'This stop wants to help you settle',
      stopFutureA: 'The you who took this road',
      stopFutureB: 'The you who took the other road',
      stopMicLead: 'What do you think? Changed your mind?',
      investigatorTitle: "Investigator's view",
      endChoiceKicker: 'Keep going?',
      endChoiceTitle: "You've walked through the stops that matter most",
      endChoiceLead: 'The remaining stops get finer-grained. You can wrap up now and see the you this walk has surfaced, or take a few more.',
      endFinish: 'Finish the journey',
      endNext: 'One more stop',
      cornerEnd: 'Finish',
      endingKicker: 'The walk is done',
      endingTitle: 'This is the you it surfaced',
      endingPortrait: 'Value portrait',
      endingShift: 'How the order moved',
      endingStart: 'Start',
      endingFinal: 'End',
      endingConf: 'After all that, how sure are you about #1?',
      endingConfWas: 'At the start',
      endingReportTitle: 'Your reflection',
      endingReplay: 'Walk it again',
      // report sections
      reKicker: 'A note',
      reTitle: 'On choices you can live with',
      reBody: ['Reflective equilibrium means your actual ranking and the things you really care about line up, instead of fighting each other.', "A choice you can live with is usually one whose cost you've seen clearly and still want to pay. After this walk, you probably know a little better what you're willing to pay for."],
      statScenesLabel: 'Stops walked',
      statScenesUnit: '',
      statLingerLabel: 'The stop that hit hardest',
      statDwellLabel: 'The stop you lingered on longest',
      statSwitchLabel: 'Order changes',
      statSwitchUnit: '',
      bumpTitle: 'How your ranking moved',
      bumpEmpty: "You barely touched the order this time.",
      bumpStart: 'Start',
      changesTitle: 'Each change, and your reason at the time',
      changesEmpty: 'You kept the same order all the way through.',
      changeReasonSaid: 'You said',
      changeTopTo: 'moved "{x}" to first',
      changeReorder: 'shuffled the order',
      changeMindTitle: 'Things that would change your mind',
      changeMindLead: 'These are the "what ifs" you said out loud after each stop.',
      changeMindEmpty: "You didn't leave many 'what ifs' this time.",
      shiftsTitle: 'The you from the start',
      shiftsLead: 'Here is what you said at the very beginning, pulled out for you to check against. What has loosened since?',
      shiftsNote: 'Telling automatically which high-level ideas shifted needs deeper language analysis. For now this shows your original words so you can look back yourself.',
      rerankWhatChanged: 'You just changed the order. What would have made you keep your earlier ranking?',
      rerankWhatSame: 'You kept the same order. What would have made you change your ranking?',
      rerankSkip: 'Skip and continue',
      loading: 'Opening the next stop…',
      backendUnavailable: 'The backend is unavailable right now. Please try again later.',
    },
  };

  const pair = (cn, en) => ({ cn, en });

  // ---- intake voice questions (besides the per-pair "what do you know" ones) ----
  const INTAKE = {
    pairs: { id: 'pairs',
      prompt: pair('先说说,你在纠结哪几个「专业@学校」?', 'First, which major@university pairs are you torn between?'),
      hint: pair('说 2 到 6 个就好,不用想得太全。', 'Two to six of them is plenty. No need to be exhaustive.') },
    perPair: {
      promptCn: (l) => `关于「${l}」,你已经知道些什么?`,
      promptEn: (l) => `What do you already know about "${l}"?`,
      hint: pair('随便聊聊你的印象、担心,或者听来的说法。', "Just share your impressions, your worries, or anything you've heard.") },
    tail: [
      { id: 'struggle',
        prompt: pair('你现在有什么纠结吗?', "Anything you're torn about right now?"),
        hint: pair('如:不同目标之间的权衡、和父母想法不一致、未来选择等。不管有多艰难或与众不同,请大胆告诉 AI 你的想法。', 'E.g. trade-offs between goals, disagreeing with your parents, choices about the future… however hard or unusual it feels, tell the AI freely.') },
      { id: 'macro',
        prompt: pair('对以后的人生,你有什么大方向上的想法?', 'For your life ahead, what do you want in the big picture?'),
        hint: pair('不用具体,说说你想要怎样的生活。', "It doesn't have to be concrete. Just the kind of life you want.") },
      { id: 'values',
        prompt: pair('钱、兴趣、影响力,你最看重哪个?', 'Money, interest, impact. Which matters most to you?'),
        hint: pair('排个序,或者说说它们之间怎么权衡。', 'Rank them, or talk through how you weigh them.') },
      { id: 'dest',
        prompt: pair('毕业以后,你更想走哪条路?国内升学、出国留学、私企就业、国企就业、考公考编、创业,还是其他?', 'After graduating, which way do you lean? Grad school in China, study abroad, a private-sector job, a state-owned job, civil service exams, starting something, or other?'),
        hint: pair('还没想好也没关系,说说倾向就行。', "It's fine to be unsure. Just your leaning.") },
      { id: 'conf',
        prompt: pair('现在,你对排在第一的那个有多确定?', 'Right now, how sure are you about your number one?'),
        hint: pair('用「不太确定」到「非常确定」之间的话说说。', 'Anywhere from "not really" to "very sure".') },
    ],
  };

  window.GK = { STR, INTAKE };
})();
